// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ6aMkrd7Bx8pU08iksqkw4OQMmPQu0nw',
    appId: '1:645553218332:web:0ac9ae064e0fec970d10d9',
    messagingSenderId: '645553218332',
    projectId: 'habit-tracer-dbe96',
    authDomain: 'habit-tracer-dbe96.firebaseapp.com',
    storageBucket: 'habit-tracer-dbe96.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWVwMxkA0UZUXYprTWzV6mxqFDpuQN8Hw',
    appId: '1:645553218332:android:471450aa9ec3dbcc0d10d9',
    messagingSenderId: '645553218332',
    projectId: 'habit-tracer-dbe96',
    storageBucket: 'habit-tracer-dbe96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkwNuC0gU83Jd46elT28Iw7ZTD01lKhTk',
    appId: '1:645553218332:ios:1855bece682695380d10d9',
    messagingSenderId: '645553218332',
    projectId: 'habit-tracer-dbe96',
    storageBucket: 'habit-tracer-dbe96.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkwNuC0gU83Jd46elT28Iw7ZTD01lKhTk',
    appId: '1:645553218332:ios:1855bece682695380d10d9',
    messagingSenderId: '645553218332',
    projectId: 'habit-tracer-dbe96',
    storageBucket: 'habit-tracer-dbe96.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ6aMkrd7Bx8pU08iksqkw4OQMmPQu0nw',
    appId: '1:645553218332:web:2da112c891e68ddd0d10d9',
    messagingSenderId: '645553218332',
    projectId: 'habit-tracer-dbe96',
    authDomain: 'habit-tracer-dbe96.firebaseapp.com',
    storageBucket: 'habit-tracer-dbe96.firebasestorage.app',
  );
}
